#!/bin/sh

# Update netlify.toml with locally installed version of node and yarn if the commit
# is a dependency update.


update_netlify_toml() {
  # Replace version of build tools in netlify.toml.
  sed -i.bak "s|$1.*|$1 = \"$2\"|" netlify.toml
}

commit_msg_file="$1"
commit_msg=$(<$commit_msg_file)
case $commit_msg in
  *"upgrade deps"*|*"upgrade dependencies"*|*"update deps"*|*"update dependencies"*)

    # Get current local node and yarn versions.
    yarn_version="$(yarn -v)"
    node_version=$(node -v)
    node_version="${node_version:1}" # Remove first character v from node version output.

    update_netlify_toml NODE_VERSION $node_version
    update_netlify_toml YARN_VERSION $yarn_version

    # Remove backup file.
    rm netlify.toml.bak

    # Stage netlify.toml for inspection. Can afterwards be added to
    # current commit by running `git commit --amend --no-edit`.
    git add netlify.toml
    echo "[commit-msg hook] Updated netlify.toml (node to $node_version, yarn to $yarn_version)"
  ;;
  esac