#!/bin/sh

# Checks staged .js and .svelte files for eslint errors.
# Exits with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

# Get list of all modified .js and .svelte files excluding deleted ones (--diff-filter=d).
files=$(git diff --cached --name-only --diff-filter=d "*.js" "*.svelte")

# Verify that changes conform to eslint rules.
echo "$files" | xargs ./node_modules/.bin/eslint

# Prevent commit in case of eslint errors (i.e. non-zero exit code).
if [[ $? != 0 ]]; then
  echo "-->" eslint error, commit denied!
  exit 1
fi
